<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mapster" Version="7.4.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.20" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="8.1.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\E_Shop.Core\E_Shop.Core.csproj" />
    <ProjectReference Include="..\E_Shop.ModelCustumes\E_Shop.Models.Custumes.csproj" />
    <ProjectReference Include="..\E_Shop.Models\E_Shop.Models.csproj" />
  </ItemGroup>

</Project>
